### PR TITLE
Db schema setup with the users table only this would help us move fast so authentication tasks can kick off

### LINKED ISSUE #1: [FEATURE] Design the database schema for Auth Module
We need a normalized database schema that takes into consideration all the tables needed to implement the authentication module of the bridge application

The schema must cater for every required table for this module, and also cater for every required column in each table

Tables should be well normalized even though it is just going to be two or three of them

This issue should be closed out as soon as possible

### PR DESCRIPTION
**Pull request by Oghenebrume50**
## Description
Setup for the users' table in the database with a diagram showing what the user table contains
dependencies  needed for this are:
- knex (install globally and locally) it would be needed to run migrations
- drawio (to view DB design on Vscode, if you use it, else you would see it as an SVG file) 
- pg (this is the Postgres client)

To work with this setup
- install Postgres and Pgadmin, if you do not have it already. 
-  create database with name bridge from your terminal
- setup env file with the relevant content as shown in .env.example
- run `npm run migrate` to create the table
- run `npm run seed` to seed the created table with provided data

A fix for (issue number 1)

## How Has This Been Tested?
Setup the database locally and generated seed files to test

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
- [ x] I have added tests that prove my fix is effective and that this feature works
- [ x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by bolubee101 — APPROVED** [review]
Good work

**Comment by Elozzy** [comment]
I love the structure

**Review by Elozzy — APPROVED** [review]

**Review by Elozzy — APPROVED** [review]
the structure looks neat. Nice job

**Review by VictorUkafor — APPROVED** [review]
Looks good

**Pull request merged**
